services:
  app:
    image: ghcr.io/vireakgami/camenu-qr-engine:prod-latest
    env_file:
      - .env
    working_dir: /var/www
    restart: unless-stopped
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "php -v || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./.env:/var/www/.env
      - storage:/var/www/storage
      - bootstrap_cache:/var/www/bootstrap/cache

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker-compose/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-net

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - app-net

  queue:
    image: ghcr.io/vireakgami/camenu-qr-engine:prod-latest
    env_file:
      - .env
    working_dir: /var/www
    command: php artisan queue:work --sleep=1 --tries=3
    depends_on:
      - app
      - redis
    restart: unless-stopped
    networks:
      - app-net
    volumes:
      - ./.env:/var/www/.env
      - storage:/var/www/storage
      - bootstrap_cache:/var/www/bootstrap/cache

  scheduler:
    image: ghcr.io/vireakgami/camenu-qr-engine:prod-latest
    env_file:
      - .env
    working_dir: /var/www
    command: sh -lc 'while true; do php artisan schedule:run --no-interaction; sleep 60; done'
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app-net
    volumes:
      - ./.env:/var/www/.env
      - storage:/var/www/storage
      - bootstrap_cache:/var/www/bootstrap/cache

networks:
  app-net:
    driver: bridge

volumes:
  storage:
  bootstrap_cache:
