services:
  app:
    image: ghcr.io/vireakgami/camenu-engine:latest
    container_name: camenu-app
    working_dir: /var/www
    restart: unless-stopped
    networks:
      - app-net
    volumes:
      - storage:/var/www/storage
      - ./.env:/var/www/.env:ro

  webserver:
    image: nginx:alpine
    container_name: camenu-web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker-compose/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-net

  redis:
    image: redis:7-alpine
    container_name: camenu-redis
    restart: unless-stopped
    networks:
      - app-net

  queue-worker:
    image: ghcr.io/vireakgami/camenu-engine:latest
    container_name: camenu-queue
    working_dir: /var/www
    command: php artisan queue:work --sleep=1 --tries=3 --queue=default,emails
    depends_on:
      - app
      - redis
    restart: unless-stopped
    networks:
      - app-net
    volumes:
      - storage:/var/www/storage
      - ./.env:/var/www/.env:ro

  scheduler:
    image: ghcr.io/vireakgami/camenu-engine:latest
    container_name: camenu-scheduler
    working_dir: /var/www
    command: sh -lc 'while true; do php artisan schedule:run --no-interaction; sleep 60; done'
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app-net
    volumes:
      - storage:/var/www/storage
      - ./.env:/var/www/.env:ro

networks:
  app-net:
    driver: bridge

volumes:
  storage: {}
