version: '3.8'

services:
  app:
    image: ghcr.io/vireakgami/camenu-engine:latest
    container_name: camenu-app
    working_dir: /var/www
    restart: unless-stopped
    depends_on:
      - mysql
      - redis
    networks:
      - app-net
    volumes:
      - storage:/var/www/storage
      - ./.env:/var/www/.env

  webserver:
    image: nginx:alpine
    container_name: camenu-web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker-compose/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-net

  mysql:
    image: mysql:8.4
    container_name: camenu-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: camenu_db
      MYSQL_USER: camenu_user
      MYSQL_PASSWORD: camenu_pass
    ports:
      - "3306:3306" # optional (remove in production if not needed)
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-net

  redis:
    image: redis:7-alpine
    container_name: camenu-redis
    restart: unless-stopped
    networks:
      - app-net

  queue-worker:
    image: ghcr.io/vireakgami/camenu-engine:latest
    container_name: camenu-queue
    working_dir: /var/www
    command: php artisan queue:work --sleep=1 --tries=3 --queue=default,emails
    depends_on:
      - app
      - redis
      - mysql
    restart: unless-stopped
    networks:
      - app-net
    volumes:
      - storage:/var/www/storage
      - ./.env:/var/www/.env

  scheduler:
    image: ghcr.io/vireakgami/camenu-engine:latest
    container_name: camenu-scheduler
    working_dir: /var/www
    command: sh -lc 'while true; do php artisan schedule:run --no-interaction; sleep 60; done'
    depends_on:
      - app
      - mysql
    restart: unless-stopped
    networks:
      - app-net
    volumes:
      - storage:/var/www/storage
      - ./.env:/var/www/.env

networks:
  app-net:
    driver: bridge

volumes:
  storage: {}
  mysql_data: {}
